### PR TITLE
remove interview requirement, use experience

### PR DESCRIPTION
**Pull request by rngadam**
As discussed, we want to recruit members with which we've actually worked for. This reflects the membership so far where most people I've added are people I've worked with.

### CODE REVIEW

**Comment by Sewerbird** [comment]
I like the removal of the formal interview requirement. Maybe clarify/allow hours spent at Codebunker (like an attendee to the co-programming sessions) as counting towards the 40-hours requirement?

**Comment by rngadam** [comment]
@Sewerbird modified

**Comment by Sewerbird** [comment]
Lgtm +1

**Comment by lenzai** [comment]
LGTM

**Pull request merged**
